services:
  server:
    build:
      context: .
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - Oauth_data:/app
    environment:
      env_file: .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"

    
    
volumes:
  Oauth_data:

